# Generated by Django 4.2.8 on 2026-03-31 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_fee_saarc', models.DecimalField(decimal_places=2, default=0, help_text='Permit fee for SAARC nationals (USD)', max_digits=8)),
                ('permit_fee_international', models.DecimalField(decimal_places=2, default=0, help_text='Permit fee for international guests (USD)', max_digits=8)),
                ('guide_daily_rate', models.DecimalField(decimal_places=2, default=30.0, help_text='Guide daily rate (USD)', max_digits=8)),
                ('porter_daily_rate', models.DecimalField(decimal_places=2, default=15.0, help_text='Porter daily rate (USD)', max_digits=8)),
                ('saarc_discount_multiplier', models.FloatField(default=0.5, help_text='Price multiplier for SAARC nationals (0.0-1.0)')),
                ('international_multiplier', models.FloatField(default=1.0, help_text='Price multiplier for international guests')),
                ('detour_premium_percent', models.FloatField(default=15.0, help_text='Additional cost % for including detours')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_config', to='api.destination')),
            ],
            options={
                'verbose_name_plural': 'Cost Configurations',
            },
        ),
        migrations.CreateModel(
            name='Detour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Mera Peak Ascent', 'Chame Hot Spring'", max_length=200)),
                ('description', models.TextField()),
                ('start_latitude', models.FloatField()),
                ('start_longitude', models.FloatField()),
                ('end_latitude', models.FloatField()),
                ('end_longitude', models.FloatField()),
                ('extra_cost_usd', models.DecimalField(decimal_places=2, help_text='Additional cost for this detour (USD)', max_digits=10)),
                ('extra_days', models.IntegerField(default=1, help_text='Additional days required for this detour')),
                ('distance_km', models.FloatField(help_text='Distance of this detour in km (for algorithm)')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging'), ('DIFFICULT', 'Difficult')], default='MODERATE', max_length=20)),
                ('quality_rating', models.FloatField(default=4.0, help_text='Quality/Beauty rating (1-5) for knapsack quality value')),
                ('is_optional', models.BooleanField(default=True, help_text='If False, detour is mandatory')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detours', to='api.destination')),
                ('required_before_detours', models.ManyToManyField(blank=True, help_text='Other detours that must be completed first (DAG edges)', related_name='dependent_detours', to='api.detour')),
            ],
            options={
                'ordering': ['destination', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrekActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('sequence_order', models.IntegerField(help_text='Order within the day')),
                ('name', models.CharField(help_text="e.g., 'Arrive at Base Camp', 'Rest day at Namche'", max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.IntegerField(help_text='Altitude in meters')),
                ('estimated_hours', models.FloatField(default=8.0, help_text='Estimated hours for this activity')),
                ('distance_from_previous_km', models.FloatField(default=0, help_text='Distance from previous activity (km)')),
                ('activity_type', models.CharField(choices=[('START', 'Trek Start'), ('WALK', 'Walking'), ('REST', 'Rest Day'), ('CAMP', 'Camp/Acclimation'), ('DETOUR', 'Detour Activity'), ('END', 'Trek End')], default='WALK', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MODERATE', 'Moderate'), ('CHALLENGING', 'Challenging')], default='MODERATE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['itinerary', 'day_number', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='TrekItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('base_cost', models.DecimalField(decimal_places=2, help_text='Base destination price (with nationality multiplier)', max_digits=12)),
                ('permit_cost', models.DecimalField(decimal_places=2, help_text='Permit fees for all people', max_digits=12)),
                ('guide_cost', models.DecimalField(decimal_places=2, default=0, help_text='Guide hiring costs', max_digits=12)),
                ('porter_cost', models.DecimalField(decimal_places=2, default=0, help_text='Porter hiring costs', max_digits=12)),
                ('detour_cost', models.DecimalField(decimal_places=2, default=0, help_text='Additional costs from detours', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total estimated trip cost (USD)', max_digits=12)),
                ('number_of_people', models.IntegerField(default=1)),
                ('include_guide', models.BooleanField(default=False)),
                ('include_porter', models.BooleanField(default=False)),
                ('number_of_porters', models.IntegerField(default=0)),
                ('total_distance_km', models.FloatField(default=0, help_text='Total trek distance including detours (km)')),
                ('total_duration_days', models.IntegerField(help_text='Total days including detours')),
                ('weather_risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20)),
                ('algorithm_used', models.CharField(blank=True, help_text="e.g., 'knapsack', 'dijkstra'", max_length=100)),
                ('execution_steps', models.JSONField(blank=True, default=list, help_text='List of steps for frontend visualization')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_itineraries', to='api.destination')),
                ('selected_detours', models.ManyToManyField(blank=True, help_text='Detours user selected for this trip', related_name='in_itineraries', to='api.detour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trek_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trek Itineraries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='destination',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(choices=[('SAARC', 'SAARC Country (Nepal, India, Pakistan, Bangladesh, Sri Lanka, Bhutan, Maldives)'), ('INTERNATIONAL', 'International')], default='INTERNATIONAL', help_text='Used for dynamic cost estimation', max_length=20),
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.AddField(
            model_name='trekactivity',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.trekitinerary'),
        ),
        migrations.AlterUniqueTogether(
            name='trekactivity',
            unique_together={('itinerary', 'day_number', 'sequence_order')},
        ),
    ]
