from django.core.management.base import BaseCommand
from api.models import Destination, TrekRoute


class Command(BaseCommand):
    help = 'Load sample trekking destinations and routes'

    def handle(self, *args, **kwargs):
        self.stdout.write('Resetting and creating Nepal trekking catalog...')

        # Keep sample data deterministic for demos.
        Destination.objects.all().delete()

        treks = [
            {
                'name': 'Luxury Everest Base Camp Trek',
                'description': 'A comfort-focused Everest route with quality lodges and guided support through Sherpa heartland to EBC.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 5364,
                'duration_days': 14,
                'difficulty': 'CHALLENGING',
                'price': 2000.00,
                'featured': True,
                'best_season': 'March-May, September-November',
                'group_size_max': 10,
                'latitude': 27.9881,
                'longitude': 86.9253,
                'route_points': [
                    (27.6881, 85.3598, 1400, 'Kathmandu', 'Arrival and briefing'),
                    (27.7000, 86.7333, 2860, 'Lukla', 'Mountain flight gateway'),
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Acclimatization hub'),
                    (27.8144, 86.7714, 3867, 'Tengboche', 'Monastery and views'),
                    (27.9006, 86.8286, 4410, 'Dingboche', 'High-altitude village'),
                    (27.9881, 86.9253, 5364, 'Everest Base Camp', 'Main destination'),
                ],
            },
            {
                'name': 'Semi-Luxury Everest Base Camp Trek',
                'description': 'Balanced comfort and adventure with improved lodges and full logistics support on the classic EBC trail.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 5364,
                'duration_days': 14,
                'difficulty': 'CHALLENGING',
                'price': 1380.00,
                'featured': True,
                'best_season': 'March-May, September-November',
                'group_size_max': 12,
                'latitude': 27.9881,
                'longitude': 86.9253,
                'route_points': [
                    (27.7000, 86.7333, 2860, 'Lukla', 'Trailhead'),
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Sherpa trading town'),
                    (27.8361, 86.7649, 4410, 'Pheriche', 'Acclimatization point'),
                    (27.9881, 86.9253, 5364, 'Everest Base Camp', 'Goal of the trek'),
                ],
            },
            {
                'name': 'Budget Everest Base Camp Trek',
                'description': 'A value-first Everest journey for budget trekkers who want a complete base camp experience.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 5364,
                'duration_days': 12,
                'difficulty': 'CHALLENGING',
                'price': 999.00,
                'featured': True,
                'best_season': 'March-May, September-November',
                'group_size_max': 15,
                'latitude': 27.9881,
                'longitude': 86.9253,
                'route_points': [
                    (27.7000, 86.7333, 2860, 'Lukla', 'Entry point to Khumbu'),
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Acclimatization stop'),
                    (27.9519, 86.8614, 5164, 'Lobuche', 'Final high camp village'),
                    (27.9881, 86.9253, 5364, 'Everest Base Camp', 'Destination reached'),
                ],
            },
            {
                'name': 'Annapurna Base Camp Trek',
                'description': 'A scenic trek through Gurung villages and rhododendron forests to the Annapurna sanctuary.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 4130,
                'duration_days': 7,
                'difficulty': 'MODERATE',
                'price': 750.00,
                'featured': True,
                'best_season': 'March-May, September-November',
                'group_size_max': 12,
                'latitude': 28.5310,
                'longitude': 83.8740,
                'route_points': [
                    (28.3949, 83.9694, 1400, 'Nayapul', 'Starting point'),
                    (28.4821, 83.8686, 2170, 'Chomrong', 'Gateway village'),
                    (28.5134, 83.8561, 3230, 'Deurali', 'High section'),
                    (28.5310, 83.8740, 4130, 'Annapurna Base Camp', 'Main camp'),
                ],
            },
            {
                'name': 'Annapurna Circuit Trek',
                'description': 'A classic trans-Himalayan route crossing Thorong La with varied landscapes and cultures.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 5416,
                'duration_days': 15,
                'difficulty': 'DIFFICULT',
                'price': 1150.00,
                'featured': False,
                'best_season': 'March-May, September-November',
                'group_size_max': 12,
                'latitude': 28.7967,
                'longitude': 83.9370,
                'route_points': [
                    (28.2333, 84.3833, 760, 'Besisahar', 'Circuit entry point'),
                    (28.6756, 84.0228, 3540, 'Manang', 'Acclimatization town'),
                    (28.7967, 83.9370, 5416, 'Thorong La Pass', 'Highest point'),
                    (28.7833, 83.7333, 3800, 'Muktinath', 'Pilgrimage destination'),
                ],
            },
            {
                'name': 'Langtang Valley Trek',
                'description': 'A culturally rich trek close to Kathmandu with glacier views and Tamang heritage settlements.',
                'location': 'Langtang Region, Nepal',
                'altitude': 3800,
                'duration_days': 8,
                'difficulty': 'MODERATE',
                'price': 650.00,
                'featured': True,
                'best_season': 'March-May, September-November',
                'group_size_max': 15,
                'latitude': 28.2164,
                'longitude': 85.5500,
                'route_points': [
                    (28.1045, 85.3231, 1460, 'Syabrubesi', 'Trek start'),
                    (28.1586, 85.4086, 2380, 'Lama Hotel', 'Forest section stop'),
                    (28.2000, 85.5000, 3430, 'Langtang Village', 'Valley settlement'),
                    (28.2164, 85.5500, 3800, 'Kyanjin Gompa', 'Final point'),
                ],
            },
            {
                'name': 'Manaslu Circuit Trek',
                'description': 'A remote and less-crowded high mountain circuit around Mount Manaslu with strong cultural depth.',
                'location': 'Manaslu Region, Nepal',
                'altitude': 5160,
                'duration_days': 14,
                'difficulty': 'DIFFICULT',
                'price': 1400.00,
                'featured': False,
                'best_season': 'March-May, September-November',
                'group_size_max': 10,
                'latitude': 28.5495,
                'longitude': 84.5595,
                'route_points': [
                    (28.2847, 84.7231, 700, 'Soti Khola', 'Start village'),
                    (28.5000, 84.5500, 3520, 'Samagaon', 'Cultural center'),
                    (28.5495, 84.5595, 5160, 'Larkya La Pass', 'Key pass crossing'),
                ],
            },
            {
                'name': 'Mardi Himal Trek',
                'description': 'A short and rewarding ridge trek with close-up views of Machhapuchhre and Annapurna South.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 4500,
                'duration_days': 6,
                'difficulty': 'MODERATE',
                'price': 520.00,
                'featured': False,
                'best_season': 'March-May, September-November',
                'group_size_max': 15,
                'latitude': 28.4260,
                'longitude': 83.9220,
                'route_points': [
                    (28.2891, 83.8175, 1070, 'Kande', 'Trailhead'),
                    (28.3897, 83.8995, 3580, 'High Camp', 'Major overnight stop'),
                    (28.4260, 83.9220, 4500, 'Mardi View Point', 'Best panorama'),
                ],
            },
            {
                'name': 'Ghorepani Poon Hill Trek',
                'description': 'A beginner-friendly trek famous for sunrise views over Annapurna and Dhaulagiri ranges.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 3210,
                'duration_days': 5,
                'difficulty': 'EASY',
                'price': 430.00,
                'featured': False,
                'best_season': 'October-November, March-April',
                'group_size_max': 18,
                'latitude': 28.3894,
                'longitude': 83.9025,
                'route_points': [
                    (28.3949, 83.9694, 1400, 'Nayapul', 'Start point'),
                    (28.3919, 83.9336, 2870, 'Ghorepani', 'Main stop'),
                    (28.3894, 83.9025, 3210, 'Poon Hill', 'Sunrise viewpoint'),
                ],
            },
            {
                'name': 'Gokyo Lakes Trek',
                'description': 'A high-altitude Khumbu trek to turquoise lakes and Gokyo Ri, offering Everest panorama without EBC crowds.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 5357,
                'duration_days': 12,
                'difficulty': 'CHALLENGING',
                'price': 1180.00,
                'featured': False,
                'best_season': 'March-May, September-November',
                'group_size_max': 10,
                'latitude': 27.9560,
                'longitude': 86.6890,
                'route_points': [
                    (27.7000, 86.7333, 2860, 'Lukla', 'Entry point'),
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Acclimatization'),
                    (27.9560, 86.6890, 4750, 'Gokyo', 'Lake settlement'),
                    (27.9615, 86.6897, 5357, 'Gokyo Ri', 'View summit'),
                ],
            },
            {
                'name': 'Upper Mustang Trek',
                'description': 'A trans-Himalayan desert trek through ancient walled villages and Tibetan-influenced culture.',
                'location': 'Mustang Region, Nepal',
                'altitude': 3840,
                'duration_days': 14,
                'difficulty': 'MODERATE',
                'price': 1850.00,
                'featured': False,
                'best_season': 'May-October',
                'group_size_max': 10,
                'latitude': 29.1878,
                'longitude': 83.9699,
                'route_points': [
                    (28.7833, 83.7333, 2720, 'Muktinath', 'Lower Mustang entry'),
                    (29.1762, 83.9590, 3810, 'Lo Manthang', 'Ancient capital'),
                    (29.1878, 83.9699, 3840, 'Chhoser', 'Cave monastery area'),
                ],
            },
            {
                'name': 'Kanchenjunga Base Camp Trek',
                'description': 'A wilderness expedition to the world\'s third-highest mountain with remote trails and pristine habitats.',
                'location': 'Kanchenjunga Region, Nepal',
                'altitude': 5143,
                'duration_days': 21,
                'difficulty': 'DIFFICULT',
                'price': 2300.00,
                'featured': False,
                'best_season': 'April-May, October-November',
                'group_size_max': 8,
                'latitude': 27.7036,
                'longitude': 88.1475,
                'route_points': [
                    (27.3544, 87.6953, 2420, 'Taplejung', 'Approach district'),
                    (27.6115, 87.9853, 3595, 'Ghunsa', 'Major settlement'),
                    (27.7036, 88.1475, 5143, 'Kanchenjunga Base Camp', 'North base camp'),
                ],
            },
        ]

        additional_treks = [
            {
                'name': 'Everest Three Passes Trek',
                'description': 'A demanding Everest adventure crossing Kongma La, Cho La, and Renjo La for full Khumbu immersion.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 5535,
                'duration_days': 18,
                'difficulty': 'DIFFICULT',
                'price': 1650.00,
                'featured': False,
                'best_season': 'April-May, October-November',
                'group_size_max': 10,
                'latitude': 27.9540,
                'longitude': 86.8210,
                'route_points': [
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Acclimatization base'),
                    (27.9540, 86.8210, 5535, 'Kongma La Pass', 'First high pass'),
                    (27.9868, 86.7430, 5420, 'Cho La Pass', 'Technical glacier pass'),
                ],
            },
            {
                'name': 'Everest Panorama Trek',
                'description': 'A shorter Everest route focused on mountain views and Sherpa culture without extreme altitude.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 3880,
                'duration_days': 9,
                'difficulty': 'MODERATE',
                'price': 820.00,
                'featured': False,
                'best_season': 'March-May, October-November',
                'group_size_max': 14,
                'latitude': 27.8144,
                'longitude': 86.7714,
                'route_points': [
                    (27.7000, 86.7333, 2860, 'Lukla', 'Trek start'),
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Sherpa town'),
                    (27.8144, 86.7714, 3867, 'Tengboche', 'View and monastery stop'),
                ],
            },
            {
                'name': 'Jiri to Everest Base Camp Trek',
                'description': 'The original classical route to Everest Base Camp from the lower hills via Jiri.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 5364,
                'duration_days': 21,
                'difficulty': 'DIFFICULT',
                'price': 1750.00,
                'featured': False,
                'best_season': 'April-May, October-November',
                'group_size_max': 10,
                'latitude': 27.9881,
                'longitude': 86.9253,
                'route_points': [
                    (27.6333, 86.2333, 1905, 'Jiri', 'Classical start point'),
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Mid-route acclimatization'),
                    (27.9881, 86.9253, 5364, 'Everest Base Camp', 'Destination'),
                ],
            },
            {
                'name': 'Everest Base Camp with Gokyo Lakes Trek',
                'description': 'A combined Everest route linking EBC and Gokyo valley via the high Cho La crossing.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 5420,
                'duration_days': 16,
                'difficulty': 'DIFFICULT',
                'price': 1520.00,
                'featured': False,
                'best_season': 'April-May, October-November',
                'group_size_max': 10,
                'latitude': 27.9868,
                'longitude': 86.7430,
                'route_points': [
                    (27.9881, 86.9253, 5364, 'Everest Base Camp', 'Main objective one'),
                    (27.9868, 86.7430, 5420, 'Cho La Pass', 'Connecting pass'),
                    (27.9560, 86.6890, 4750, 'Gokyo', 'Main objective two'),
                ],
            },
            {
                'name': 'Ama Dablam Base Camp Trek',
                'description': 'A moderate Khumbu trek to the stunning base of Ama Dablam with Everest region views.',
                'location': 'Khumbu Region, Nepal',
                'altitude': 4600,
                'duration_days': 11,
                'difficulty': 'CHALLENGING',
                'price': 1080.00,
                'featured': False,
                'best_season': 'March-May, October-November',
                'group_size_max': 12,
                'latitude': 27.8614,
                'longitude': 86.8610,
                'route_points': [
                    (27.7397, 86.7147, 3440, 'Namche Bazaar', 'Acclimatization'),
                    (27.8361, 86.7649, 4410, 'Pangboche', 'Traditional village'),
                    (27.8614, 86.8610, 4600, 'Ama Dablam Base Camp', 'Final camp'),
                ],
            },
            {
                'name': 'Annapurna Circuit with Tilicho Lake Trek',
                'description': 'An Annapurna Circuit variant including Tilicho Lake, one of the world\'s highest lakes.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 5416,
                'duration_days': 17,
                'difficulty': 'DIFFICULT',
                'price': 1320.00,
                'featured': False,
                'best_season': 'April-May, October-November',
                'group_size_max': 12,
                'latitude': 28.6768,
                'longitude': 83.8121,
                'route_points': [
                    (28.6756, 84.0228, 3540, 'Manang', 'Circuit midpoint'),
                    (28.6768, 83.8121, 4919, 'Tilicho Lake', 'High lake detour'),
                    (28.7967, 83.9370, 5416, 'Thorong La Pass', 'Circuit high pass'),
                ],
            },
            {
                'name': 'Nar Phu Valley Trek',
                'description': 'A restricted-area trek through remote medieval villages north of the Annapurna range.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 5320,
                'duration_days': 14,
                'difficulty': 'DIFFICULT',
                'price': 1480.00,
                'featured': False,
                'best_season': 'May-June, September-November',
                'group_size_max': 10,
                'latitude': 28.7858,
                'longitude': 84.0608,
                'route_points': [
                    (28.6756, 84.0228, 3540, 'Manang', 'Main access point'),
                    (28.7575, 84.1071, 4080, 'Phu Gaon', 'Ancient village'),
                    (28.7858, 84.0608, 5320, 'Kang La Pass', 'Pass to rejoin circuit'),
                ],
            },
            {
                'name': 'Khopra Danda Trek',
                'description': 'A quiet community-lodge trek with dramatic Dhaulagiri and Annapurna views.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 3660,
                'duration_days': 7,
                'difficulty': 'MODERATE',
                'price': 620.00,
                'featured': False,
                'best_season': 'March-May, October-November',
                'group_size_max': 15,
                'latitude': 28.4440,
                'longitude': 83.7850,
                'route_points': [
                    (28.3949, 83.9694, 1400, 'Nayapul', 'Trail start'),
                    (28.4090, 83.8470, 2870, 'Swarna Village', 'Ridge village'),
                    (28.4440, 83.7850, 3660, 'Khopra Danda', 'Main viewpoint ridge'),
                ],
            },
            {
                'name': 'Annapurna Sanctuary Trek',
                'description': 'A classic mountain amphitheater trek deep into the Annapurna Sanctuary.',
                'location': 'Annapurna Region, Nepal',
                'altitude': 4130,
                'duration_days': 10,
                'difficulty': 'CHALLENGING',
                'price': 890.00,
                'featured': False,
                'best_season': 'March-May, October-November',
                'group_size_max': 12,
                'latitude': 28.5310,
                'longitude': 83.8740,
                'route_points': [
                    (28.4821, 83.8686, 2170, 'Chomrong', 'Approach village'),
                    (28.5134, 83.8561, 3230, 'Deurali', 'Sanctuary entry'),
                    (28.5310, 83.8740, 4130, 'Annapurna Base Camp', 'Sanctuary center'),
                ],
            },
            {
                'name': 'Pikey Peak Trek',
                'description': 'A lower-Everest hill trek known for sunrise Everest panoramas and cultural trails.',
                'location': 'Solu Region, Nepal',
                'altitude': 4065,
                'duration_days': 6,
                'difficulty': 'MODERATE',
                'price': 560.00,
                'featured': False,
                'best_season': 'March-May, October-December',
                'group_size_max': 16,
                'latitude': 27.5431,
                'longitude': 86.3738,
                'route_points': [
                    (27.5500, 86.3167, 2850, 'Jhapre', 'Village start'),
                    (27.5400, 86.3600, 3640, 'Pikey Base Camp', 'Camp area'),
                    (27.5431, 86.3738, 4065, 'Pikey Peak', 'Sunrise viewpoint'),
                ],
            },
            {
                'name': 'Langtang Gosaikunda Trek',
                'description': 'A combined Langtang and sacred lake route crossing high Lauribina Pass terrain.',
                'location': 'Langtang Region, Nepal',
                'altitude': 4610,
                'duration_days': 12,
                'difficulty': 'CHALLENGING',
                'price': 980.00,
                'featured': False,
                'best_season': 'April-June, September-November',
                'group_size_max': 12,
                'latitude': 28.0872,
                'longitude': 85.4157,
                'route_points': [
                    (28.2164, 85.5500, 3800, 'Kyanjin Gompa', 'Langtang upper valley'),
                    (28.0872, 85.4157, 4380, 'Gosaikunda', 'Sacred alpine lake'),
                    (28.0388, 85.3962, 4610, 'Lauribina Pass', 'High crossing'),
                ],
            },
            {
                'name': 'Tamang Heritage Trail',
                'description': 'A culturally immersive trek through Tamang villages with homestays and mountain views.',
                'location': 'Langtang Region, Nepal',
                'altitude': 3165,
                'duration_days': 7,
                'difficulty': 'EASY',
                'price': 480.00,
                'featured': False,
                'best_season': 'March-May, October-November',
                'group_size_max': 18,
                'latitude': 28.1330,
                'longitude': 85.3170,
                'route_points': [
                    (28.1045, 85.3231, 1460, 'Syabrubesi', 'Start village'),
                    (28.1330, 85.3170, 2238, 'Gatlang', 'Tamang settlement'),
                    (28.1880, 85.3390, 3165, 'Nagyang', 'High heritage point'),
                ],
            },
            {
                'name': 'Helambu Trek',
                'description': 'A short trek near Kathmandu with Hyolmo culture, forests, and broad mountain views.',
                'location': 'Helambu Region, Nepal',
                'altitude': 3650,
                'duration_days': 6,
                'difficulty': 'EASY',
                'price': 470.00,
                'featured': False,
                'best_season': 'March-May, September-November',
                'group_size_max': 18,
                'latitude': 28.0284,
                'longitude': 85.5600,
                'route_points': [
                    (27.8643, 85.5124, 2000, 'Sundarijal', 'Trailhead'),
                    (27.9610, 85.5420, 2470, 'Kutumsang', 'Village stop'),
                    (28.0284, 85.5600, 3650, 'Tharepati', 'High point'),
                ],
            },
            {
                'name': 'Ruby Valley Trek',
                'description': 'A less-traveled mid-hill route between Langtang and Manaslu regions with local culture.',
                'location': 'Dhading-Rasuwa Region, Nepal',
                'altitude': 3850,
                'duration_days': 9,
                'difficulty': 'MODERATE',
                'price': 690.00,
                'featured': False,
                'best_season': 'March-May, October-November',
                'group_size_max': 14,
                'latitude': 28.2350,
                'longitude': 84.9600,
                'route_points': [
                    (28.0740, 85.2000, 1500, 'Syabru Besi Roadhead', 'Entry area'),
                    (28.1790, 85.0560, 2930, 'Somdang', 'Traditional settlement'),
                    (28.2350, 84.9600, 3850, 'Pangsang Pass', 'Main viewpoint'),
                ],
            },
            {
                'name': 'Tsum Valley Trek',
                'description': 'A sacred hidden valley trek rich in Tibetan Buddhist heritage and remote landscapes.',
                'location': 'Manaslu Region, Nepal',
                'altitude': 3700,
                'duration_days': 15,
                'difficulty': 'CHALLENGING',
                'price': 1350.00,
                'featured': False,
                'best_season': 'March-May, September-November',
                'group_size_max': 10,
                'latitude': 28.6160,
                'longitude': 84.8390,
                'route_points': [
                    (28.4000, 84.7000, 1340, 'Arughat', 'Approach area'),
                    (28.5690, 84.8390, 3240, 'Chumling', 'Lower Tsum'),
                    (28.6160, 84.8390, 3700, 'Mu Gompa', 'Upper valley monastery'),
                ],
            },
            {
                'name': 'Dhaulagiri Circuit Trek',
                'description': 'A technical and wild high-altitude circuit around Dhaulagiri massif.',
                'location': 'Dhaulagiri Region, Nepal',
                'altitude': 5360,
                'duration_days': 17,
                'difficulty': 'DIFFICULT',
                'price': 1950.00,
                'featured': False,
                'best_season': 'April-May, September-October',
                'group_size_max': 8,
                'latitude': 28.7110,
                'longitude': 83.3830,
                'route_points': [
                    (28.5160, 83.6600, 1100, 'Beni', 'Expedition start'),
                    (28.7110, 83.3830, 5360, 'French Pass', 'Highest crossing'),
                    (28.7300, 83.4300, 5200, 'Dhampus Pass', 'Second high pass'),
                ],
            },
            {
                'name': 'Upper Dolpo Trek',
                'description': 'A remote trans-Himalayan wilderness trek through isolated valleys and ancient Bon culture.',
                'location': 'Dolpo Region, Nepal',
                'altitude': 5350,
                'duration_days': 24,
                'difficulty': 'DIFFICULT',
                'price': 2950.00,
                'featured': False,
                'best_season': 'May-October',
                'group_size_max': 8,
                'latitude': 29.2024,
                'longitude': 82.9695,
                'route_points': [
                    (29.0422, 82.8189, 2490, 'Juphal', 'Entry point'),
                    (29.2024, 82.9695, 3611, 'Shey Gompa', 'Cultural center'),
                    (29.2140, 83.0000, 5350, 'Kang La Pass', 'Remote high pass'),
                ],
            },
            {
                'name': 'Rara Lake Trek',
                'description': 'A peaceful western Nepal trek to the country\'s largest lake within alpine forest.',
                'location': 'Mugu Region, Nepal',
                'altitude': 3010,
                'duration_days': 8,
                'difficulty': 'EASY',
                'price': 760.00,
                'featured': False,
                'best_season': 'April-June, September-November',
                'group_size_max': 16,
                'latitude': 29.5300,
                'longitude': 82.0900,
                'route_points': [
                    (29.0422, 82.8189, 2490, 'Juphal', 'Approach airport area'),
                    (29.4740, 82.1260, 2990, 'Rara National Park', 'Park entry'),
                    (29.5300, 82.0900, 3010, 'Rara Lake', 'Main destination'),
                ],
            },
            {
                'name': 'Makalu Base Camp Trek',
                'description': 'A challenging route to the foot of Makalu through deep valleys and high ridges.',
                'location': 'Makalu Region, Nepal',
                'altitude': 4870,
                'duration_days': 20,
                'difficulty': 'DIFFICULT',
                'price': 2450.00,
                'featured': False,
                'best_season': 'April-May, October-November',
                'group_size_max': 8,
                'latitude': 27.8890,
                'longitude': 87.1120,
                'route_points': [
                    (27.3370, 87.2170, 840, 'Tumlingtar', 'Access point'),
                    (27.7240, 87.1620, 3550, 'Khongma Danda', 'Ridge crossing'),
                    (27.8890, 87.1120, 4870, 'Makalu Base Camp', 'Final camp'),
                ],
            },
            {
                'name': 'Kanchenjunga South Base Camp Trek',
                'description': 'A remote approach to Kanchenjunga\'s southern face through alpine forests and villages.',
                'location': 'Kanchenjunga Region, Nepal',
                'altitude': 4730,
                'duration_days': 19,
                'difficulty': 'DIFFICULT',
                'price': 2250.00,
                'featured': False,
                'best_season': 'April-May, October-November',
                'group_size_max': 8,
                'latitude': 27.6750,
                'longitude': 88.0600,
                'route_points': [
                    (27.3544, 87.6953, 2420, 'Taplejung', 'Approach region'),
                    (27.5260, 87.9480, 3120, 'Yamphudin', 'South route village'),
                    (27.6750, 88.0600, 4730, 'South Base Camp', 'Main destination'),
                ],
            },
        ]

        treks.extend(additional_treks)

        destinations_created = 0
        route_points_created = 0

        for trek in treks:
            route_points = trek.pop('route_points')
            destination = Destination.objects.create(**trek)
            destinations_created += 1

            for sequence, (lat, lon, alt, location_name, description) in enumerate(route_points, start=1):
                TrekRoute.objects.create(
                    destination=destination,
                    sequence_order=sequence,
                    latitude=lat,
                    longitude=lon,
                    altitude=alt,
                    location_name=location_name,
                    description=description,
                )
                route_points_created += 1

        self.stdout.write(self.style.SUCCESS('Nepal trekking catalog loaded successfully.'))
        self.stdout.write(f'Created {destinations_created} destinations')
        self.stdout.write(f'Created {route_points_created} route points')
